### ISSUE TITLE
the .layout and .depends file should not be put in the git repo

### ISSUE THREAD

**Issue by asmwarrior** [yan9a/wxwidgets#2]
Hi,

`.layout` stores the window layout, `.depends` stores the build dependencies. Those files are automatically generated by Code::Blocks when running or compiling.
Generally, a single `.cbp` file is enough for a Code::Blocks project.

The issue also exits in your another repo: https://github.com/yan9a/ceutil

**Comment by yan9a** [comment]
Thanks for the feedback. I will remove them and get back to the issue to close.

**Comment by yan9a** [comment]
Removed and added gitignore

**Comment by asmwarrior** [comment]
There is one layout file in wxtest folder.

**Comment by yan9a** [comment]
Thanks again. wxtest.layout now removed.
